### ISSUE TITLE
Usage instruction

### ISSUE THREAD

**Issue by aandis** [sighingnow/jekyll-gitbook#1]
There's no `Gemfile` in this theme's repo. How does one setup this theme into a jekyll site?

**Comment by sighingnow** [comment]
The `jekyll-gitbook` package is a not a ruby (gem) package. It is designed for github pages. I'm not familiar with using jekyll in `Gemfile`, but I think the `_config.yaml` should be enough for a jekyll project, just like what the github pages does.

For the usage instruction, just fork this repo, add your own markdown documents, then it could be previewed via github pages site, e.g., `https://xxxx.github.io/xxxx`.
