### ISSUE TITLE
Cannot jump into some tocs ?

### ISSUE THREAD

**Issue by ZenMoore** [sighingnow/jekyll-gitbook#10]
See here : https://zenmoore.github.io/note/2021-08-13-notenlppretrainedhit.html
When I click the toc, "I.任务层级" for example, it cannot jump into the right place.
In fact, it doesn't act at all. T_T
How to deal with it ?

**Comment by sighingnow** [comment]
The `min` and `max` level for TOC is configurable, see

https://github.com/sighingnow/jekyll-gitbook/blob/master/_config.yml#L18
