### ISSUE TITLE
wish this will support tags and latex syntax

### ISSUE THREAD

**Issue by swithun-liu** [sighingnow/jekyll-gitbook#104]
wish this will support tags and latex syntax

**Comment by sighingnow** [comment]
Could you show some examples for such markup?

**Comment by swithun-liu** [comment]
1. for latex
like this one 
<img width="1109" alt="image" src="https://github.com/sighingnow/jekyll-gitbook/assets/42160297/507224f3-4696-40ee-b6c4-398a8a513326">
http://jekyllthemes.org/themes/jekyll-yamt/

here is notion example
<img width="989" alt="image" src="https://github.com/sighingnow/jekyll-gitbook/assets/42160297/053af046-bb86-4f97-92a7-0f91a26f70bd">
two kinds of block -- inline version and whole block version

<img width="972" alt="image" src="https://github.com/sighingnow/jekyll-gitbook/assets/42160297/7877caf2-3e37-40b0-9f59-a6e0fb7128e1">


2. for tags
https://chirpy.cotes.page/tags/
like this one ⬆️

**Comment by sighingnow** [comment]
The mathjax support has been fixed and an example has been added: https://sighingnow.github.io/jekyll-gitbook/jekyll/2023-10-14-math-latex.html

**Comment by sighingnow** [comment]
Tags won't be supported. If I understand it correctly, the original gitbook which we referred from doesn't have tags as well.
