### ISSUE TITLE
Ask for help with styles

### ISSUE THREAD

**Issue by Happier0120** [sighingnow/jekyll-gitbook#106]
I want to know why css styles are not working.
![image](https://github.com/sighingnow/jekyll-gitbook/assets/34394931/ea4c7af8-1d4a-451b-9601-a0e71ae18c21)

**Comment by sighingnow** [comment]
Where could I find the repo to take a look?

**Comment by Happier0120** [comment]
https://github.com/Happier0120/Happier0120.github.io
This is my repo.
Thx.

**Comment by sighingnow** [comment]
You need change the `baseurl` in your `_config.yml` to `/`:

https://github.com/Happier0120/Happier0120.github.io/blob/master/_config.yml
