### ISSUE TITLE
Footnotes not linking

### ISSUE THREAD

**Issue by catherinecanfly** [sighingnow/jekyll-gitbook#109]
Hello there!
I have a question hoping for help! Any pointers are immensely appreciated! Thank you very much!
The footnotes on my page refuse to go to the appropriate place at the bottom of the page. I really cannot figure out what is preventing it so. [https://offingbloom.com/ob-v1/2023-07-16-prologue.html](https://offingbloom.com/ob-v1/2023-07-16-prologue.html) 
The footnote appears to be written correctly as such:
Tanhua[1](https://github.com/catherinecanfly/Heartbloom/blob/main/_posts/2023-07-16-prologue.md#user-content-fn-1-d4cf076c740d9e9f8c914b50cc84778f)
But it doesn't scroll on the website. I am not quite sure this is.

Thank you kindly for your time!

**Comment by sighingnow** [comment]
Will take a look. Thanks for raising the issue.

**Comment by sighingnow** [comment]
Fixed. The usage of footnotes can be previewed at: https://sighingnow.github.io/jekyll-gitbook/jekyll/2023-12-12-footnotes.html

(You may need to force refresh the browser caches).

**Comment by catherinecanfly** [comment]
> Fixed. The usage of footnotes can be previewed at: https://sighingnow.github.io/jekyll-gitbook/jekyll/2023-12-12-footnotes.html
> 
> (You may need to force refresh the browser caches).

Hello, it still only  works when I refresh the page. Is there a way to avoid this? I wish it can work without needing to refresh a page, because users won't know that they need to refresh, they would just assume it doesn't work. Thank you so much for looking into it!

**Comment by sighingnow** [comment]
>  I changed the theme.js and gitbook.js and added the lines in body.html as well. I'm unsure why this still doesn't run.

Make sure you have cleared the browser's cache for your site.

**Comment by catherinecanfly** [comment]
Thank you! It worked :)

**Comment by catherinecanfly** [comment]
Hello there, I tested again and discovered that the footnotes doesn't work on chrome on iOS mobile or iPad. Would you know how to fix this? Thank you so much!
