### ISSUE TITLE
Add pages not shown on TOC

### ISSUE THREAD

**Issue by catherinecanfly** [sighingnow/jekyll-gitbook#111]
Hello there, how can I add a page (searchable or linkable in site) that doesn't show up on the Toc? I tried to add a page as a link to the bottom of the toc footer using the post/home layouts, but they would show up was 404. If I need to make a new layout for these pages,how can I do this, and where do I change on the new layout html? Thank you so much for your time and help!

**Comment by sighingnow** [comment]
May I find the problematic repo somewhere?

**Comment by catherinecanfly** [comment]
Hello, please see the repo here: https://github.com/catherinecanfly/Heartbloom
Sorry I removed the said problematic page, the question I am posing now is currently hypothetical as to how I can add a page that won’t show on the side TOC. Or, if I add another category in addition to pages/posts, so there is an additional category on the TOC. Thank you so much!

**Comment by sighingnow** [comment]
If you would like to add other collections, you would need to modify the configuration here:

https://github.com/catherinecanfly/Heartbloom/blob/main/_config.yml#L52

By default there's only `_pages`.

**Comment by sighingnow** [comment]
`_posts` is the default collection.

**Comment by sighingnow** [comment]
See also: https://jekyllrb.com/docs/collections/

**Comment by catherinecanfly** [comment]
So if I want to a collection called back-matter, do I add another collection on config and can I still use the post layout? Or do I need to add another layout?

**Comment by sighingnow** [comment]
> So if I want to a collection called back-matter, do I add another collection on config and can I still use the post layout?

You need to add a `back-matter` entry to the config file, and you still can use the default `_posts` directory.

**Comment by catherinecanfly** [comment]
Thank you for the explanation!


Sent from Yahoo Mail for iPhone


On Sunday, December 17, 2023, 10:56 pm, Tao He ***@***.***> wrote:





So if I want to a collection called back-matter, do I add another collection on config and can I still use the post layout?


You need to add a back-matter entry to the config file, and you still can use the default _posts directory.
