### ISSUE TITLE
左边目录收缩功能

### ISSUE THREAD

**Issue by zhpower** [sighingnow/jekyll-gitbook#112]
theme用起来简洁大方，非常舒服。 就是发现如果目录层次多的时候，有些不方便。如果能添加**收缩展开**功能就更好了。
![1](https://github.com/sighingnow/jekyll-gitbook/assets/1697682/49a39e79-10d5-4891-96db-184c6387922f)

**Comment by sighingnow** [comment]
可以的，我看看哈

**Comment by sighingnow** [comment]
Implemented.

**Comment by zhpower** [comment]
下载了试了一下，可以工作。 谢谢！
发现一个小瑕疵， 就是如果目录结构层次较多时，较深的几层点击不能收缩。
![2](https://github.com/sighingnow/jekyll-gitbook/assets/1697682/70f676b7-f9dd-4d44-bf0a-52d402cfa88b)

我修改了如下文件来加入较多的层次结构
![3](https://github.com/sighingnow/jekyll-gitbook/assets/1697682/e4105a16-ab12-4e94-9e63-77f967f8424b)
![4](https://github.com/sighingnow/jekyll-gitbook/assets/1697682/0411d0d3-4a93-4ca4-8a9f-734ec2a3948c)
