### ISSUE TITLE
How to add categories?

### ISSUE THREAD

**Issue by daniel00** [sighingnow/jekyll-gitbook#113]
How to add categories?
Is there any document?
Thank you

**Comment by sighingnow** [comment]
Would take a try about jekyll categories.

**Comment by digitalfredy** [comment]
If it is useful, this is my use case:

We are doing a process and procedures manual for a non profit organization, our idea was use categories to separate process from procedures and to have a clear view in the main menu.

I was expecting something like:

```
Search
----------------
Home
----------------
About
Other page
----------------
Process (Category 1)
  Post1 Cat1
  Post2 Cat1
Procedures  (Category 2)
  Post1 Cat2
  Post2 Cat2
```

**Comment by digitalfredy** [comment]
As workaround I created a page per category and for now I'm doing the category index manually but almost sure I will write a script to generate those category pages.

Not sure if useful but managing categories as pages could be another way to address this issue.

**Comment by sighingnow** [comment]
Indentation between files won't be supported, I think.

Closing as discussed in https://github.com/sighingnow/jekyll-gitbook/issues/100#issuecomment-1959801428
