### ISSUE TITLE
toc not enabled for home page

### ISSUE THREAD

**Issue by Avikam03** [sighingnow/jekyll-gitbook#136]
hi! thanks for creating this.

can you add functionality to enable toc for the home page? noticed that toc is only generated for posts and not the home page (README.md).

i understand if everyone wouldn't want this feature – so a flag to enable/disable it would probably be the best way to go about it (with the default being disabled, for now).

thank you!

**Comment by sighingnow** [comment]
Fixed by #137. Thank you @Avikam03 !
