### ISSUE TITLE
Chinese search & night mode display

### ISSUE THREAD

**Issue by Oreomeow** [sighingnow/jekyll-gitbook#14]
1. Can the search box support Chinese search?

2. If the markdown file contains syntax highlighting, it will be difficult to distinguish the background color from some code color when night mode is turned on.
  - e.g. `[` & `]` in `if [ -n "$a" ]`

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by sighingnow** [comment]
> * Can the search box support Chinese search?
> *

It worths a try.

**Comment by sighingnow** [comment]
> 1. Can the search box support Chinese search?

I have re-implementation the "search" button by using the gitbook-plugin-search-pro plugin. Now it yields the exactly same behavior.

> 2. If the markdown file contains syntax highlighting, it will be difficult to distinguish the background color from some code color when night mode is turned on.
> 
> * e.g. `[` & `]` in `if [ -n "$a" ]`
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

The syntax highlighting style is configurable via the entry `syntax_highlighter_style` in `_config.yml`.
