### ISSUE TITLE
GitHub Build Failure

### ISSUE THREAD

**Issue by mcc-us** [sighingnow/jekyll-gitbook#144]
I recently downloaded a zip file from your repo for a new GitHub Pages site. I have the settings properly set for GH Pages, etc. However, when I push the files for my new website, I get a GitHub Build Failure. 
Error Below...
Is this a Jekyll issue or Github one.
Any help would be greatly appreciated.
TY

I receive this error:
Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v232 GitHub Pages: jekyll v3.10.0 

Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-feed Requiring: jekyll-readme-index Requiring: jemoji Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings Requiring: jekyll-remote-theme GitHub Metadata: Initializing... Source: /github/workspace/./ Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... Theme: sighingnow/jekyll-gitbook Theme source: /tmp/jekyll-remote-theme-20240920-9-kzcn0v Remote Theme: Using theme sighingnow/jekyll-gitbook Remote Theme: Downloading https://codeload.github.com/sighingnow/jekyll-gitbook/zip/HEAD to /tmp/jekyll-remote-theme-20240920-9-xmoqbu.zip Remote Theme: Unzipping /tmp/jekyll-remote-theme-20240920-9-xmoqbu.zip to /tmp/jekyll-remote-theme-20240920-9-kzcn0v 

Reading: _posts/2024-08-15-free-filing-info.md Reading: _pages/001-pub17.tax.guide.md Reading: _pages/002-see-1-notes.md Reading: _pages/1.pdf2table.md Reading: _pages/9999-matts-html-help.md

**Comment by byhlel** [comment]
I had similar issues, just try to use github actions to deploy your site instead and it should work just fine.
The automatic deploy is not really up to date regarding Jekyll amongst other things.

**Comment by mcc-us** [comment]
You're right. Thanks
I think I also changed the Jekyll.yaml for the Github actions, which caused an issue.
