### ISSUE TITLE
Start and 404 page bug.

### ISSUE THREAD

**Issue by tamasg** [sighingnow/jekyll-gitbook#15]
Hello,

i made a fork and tried it. I think I found a little bug. I attached the pictures. Appears on start page and page 404 only.

![local_start](https://user-images.githubusercontent.com/5910815/150307171-cdce224e-11a6-4f94-a9cd-f68117191a65.png)
![sample_start](https://user-images.githubusercontent.com/5910815/150307174-bcc8e340-2757-42ae-a39b-9cd711e5cd2a.png)
![sample_404](https://user-images.githubusercontent.com/5910815/150307172-5a07caf9-84c5-4058-8d1e-f3cbf6a8986e.png)

I think the bug to include search.html twice in the home layout. If I toggle line comment, it works fine.

![twice_include_search_html](https://user-images.githubusercontent.com/5910815/150307329-5957488c-6811-485d-a468-45c4664a4d89.png)

Tamas

**Comment by sighingnow** [comment]
Thanks!

It is definitely a bug.

**Comment by sighingnow** [comment]
Fixed in master.
