### ISSUE TITLE
Previous <> Next bug

### ISSUE THREAD

**Issue by tamasg** [sighingnow/jekyll-gitbook#16]
Hello,

if there is not enough content.

Tamas

![arrows](https://user-images.githubusercontent.com/5910815/150626027-1cf110f8-c2c3-4325-854e-0b29687a1c73.png)

**Comment by sighingnow** [comment]
Thanks!

**Comment by sighingnow** [comment]
I'm looking into these two issues.

**Comment by sighingnow** [comment]
Fixed in master. I think the behaviour is inherited from gitbook, but I agree we could do better. Now it looks as

![image](https://user-images.githubusercontent.com/7144772/150632068-2b6cddd7-70f4-4d26-81fb-528f8c635e6e.png)
