### ISSUE TITLE
A quick return to top button

### ISSUE THREAD

**Issue by Oreomeow** [sighingnow/jekyll-gitbook#17]
Thanks for adding the search plugin!
Would it be possible to add a quick return to top button? When an article is too long, I add a table of contents with jumpable links at the top and when I get very far down the article, I would like to be able to quickly return to the top table of contents.

**Comment by sighingnow** [comment]
I could add such a button this weekend.

**Comment by sighingnow** [comment]
Hi @Oreomeow,

Such a "back-to-top" button has been added and can be previewed from  https://sighingnow.github.io/jekyll-gitbook/.

**Comment by Oreomeow** [comment]
Grateful for your efforts!
