### ISSUE TITLE
Secure up the `book-header`

### ISSUE THREAD

**Issue by bopoh13** [sighingnow/jekyll-gitbook#18]
Is it possible to freeze the position of panel `book-header` so that page scrolling doesn't affect it?

![Screenshot_2022-03-25-18-25-00](https://user-images.githubusercontent.com/6163937/160162294-512c94c0-7288-4c4b-a5ac-44185c8a45e1.jpg)

For articles the button `back-to-top` is suitable, but not for documentation. In addition active partition is highlighted in the menu.

Thanks for the minimalistic template!

**Comment by sighingnow** [comment]
> Is it possible to freeze the position of panel `book-header` so that page scrolling doesn't affect it?
> ...
> Thanks for the minimalistic template!

Implemented on the HEAD.

**Comment by Oreomeow** [comment]
However it won't jump when you click on the sub toc on mobile. I recommend this plugin repository: gitbook-plugin-anchor-navigation-ex for both top return and quick positioning. And it is not affected by page scrolling.

**Comment by sighingnow** [comment]
> Reference in new

I have fixed the issue and commented under #19.
