### ISSUE TITLE
Can't jump when you click on the left sub toc (e.g. why this repo) on mobile

### ISSUE THREAD

**Issue by Oreomeow** [sighingnow/jekyll-gitbook#19]
After https://github.com/sighingnow/jekyll-gitbook/commit/0cbb5a29d6d837b405ada1b3886c27ad1c48bf4b #18 
However it won't jump when you click on the left sub toc (e.g. why this repo) on mobile. I recommend this plugin repository: gitbook-plugin-anchor-navigation-ex for both top return and quick positioning. And it is not affected by page scrolling.

**Comment by sighingnow** [comment]
> After [0cbb5a2](https://github.com/sighingnow/jekyll-gitbook/commit/0cbb5a29d6d837b405ada1b3886c27ad1c48bf4b) #18 However it won't jump when you click on the left sub toc (e.g. why this repo) on mobile. I recommend this plugin repository: gitbook-plugin-anchor-navigation-ex for both top return and quick positioning. And it is not affected by page scrolling.

Thanks for pointing me that, I will take a try.

**Comment by sighingnow** [comment]
> After [0cbb5a2](https://github.com/sighingnow/jekyll-gitbook/commit/0cbb5a29d6d837b405ada1b3886c27ad1c48bf4b) #18 However it won't jump when you click on the left sub toc (e.g. why this repo) on mobile. I recommend this plugin repository: gitbook-plugin-anchor-navigation-ex for both top return and quick positioning. And it is not affected by page scrolling.

Hi @Oreomeow,

The nav link issue should be fixed on master.

The plugin "gitbook-plugin-anchor-navigation-ex" looks nice, but I think the UI provides by this plugin is orthogonal with bug raised when implementing #18.

**Comment by Oreomeow** [comment]
Thanks for quick fix!
