### ISSUE TITLE
If you don't  mind, Would I ask about how to use the Google Analytics option?

### ISSUE THREAD

**Issue by Jerrykim91** [sighingnow/jekyll-gitbook#22]
Thank you for making this theme. I love it. thank you.

Well ... I wanna use Google Analytics option in this theme. 
If you don't  mind, Would I ask about how to use the Google Analytics option?

**Comment by sighingnow** [comment]
Nice feature, I could add an option for it.

**Comment by sighingnow** [comment]
> Nice feature, I could add an option for it.

Added in https://github.com/sighingnow/jekyll-gitbook/commit/b9142ac36cb298ba5ac9efe01f5b5b95ea865ab3.

**Comment by Jerrykim91** [comment]
It works! Thank you. 
Would  I ask you one more thing? Um, It too hard to change that code for myself. 
please hlep me. 

I usually use mobile mode. But when it's on mobile mode, searching is a bit uncomfortable
Is it possible to improve it?

![image](https://user-images.githubusercontent.com/52520780/163148585-51268c30-556d-4e61-827d-401bf063e52a.png)

**Comment by sighingnow** [comment]
> I usually use mobile mode. But when it's on mobile mode, searching is a bit uncomfortable
> Is it possible to improve it?

Of course yes, but won't be done before this weekend.

**Comment by sighingnow** [comment]
> It works! Thank you. Would I ask you one more thing? Um, It too hard to change that code for myself. please hlep me.
> 
> I usually use mobile mode. But when it's on mobile mode, searching is a bit uncomfortable Is it possible to improve it?

Now we have a standalone page for search on mobile devices: https://sighingnow.github.io/jekyll-gitbook/search.html?q=generated

**Comment by Jerrykim91** [comment]
Oh, that's a really cool feature.😍 Thank you very much. 
I also tried the mobile function, but it didn't work. lol🤣
I will use it well. Thank you.

**Comment by sighingnow** [comment]
> but it didn't work. lol🤣

I cannot see why it doesn't work on mobile devices. I have added a "click to search" button as well as a search page for mobile devices and have tested it on my own phone.

Would you mind pasting some snapshots here? I could take a look and try fixing that.

**Comment by Jerrykim91** [comment]
Oh, 
I mean when I first request for making the mobile function!
It works very well NOW! lol Thank you!
