### ISSUE TITLE
Query problem

### ISSUE THREAD

**Issue by moluranli** [sighingnow/jekyll-gitbook#29]
If I jump to a page and query the information of this page, click the link, it will suddenly jump, and then immediately jump back to the query page, I don't know if it is my certain configuration problem

![20220506143345](https://user-images.githubusercontent.com/77564239/167079531-dbabe9d8-965f-43ef-9d51-8cad6e5049d0.png)

**Comment by sighingnow** [comment]
Do you have any living links that I can try to reproduce the trouble?

Thanks!

**Comment by moluranli** [comment]
Here is my GitPage link, thanks for your help
[https://moluranli.github.io/](https://moluranli.github.io/)

**Comment by moluranli** [comment]
This is my warehouse address, which may help you find some problems. I am sorry that I am not familiar with relevant codes
[https://github.com/moluranli/moluranli.github.io](https://github.com/moluranli/moluranli.github.io)

**Comment by sighingnow** [comment]
Fixed in https://github.com/sighingnow/jekyll-gitbook/commit/9484194283953ecfb8ccc9bd776fa844b54b25ea
