### ISSUE TITLE
support for cover images [Feature Request]

### ISSUE THREAD

**Issue by ShibeFaceSkrill** [sighingnow/jekyll-gitbook#32]
gitbook allows for cover images.. would be great to see support for that here, thanks!

example:
![Screenshot from 2022-05-20 01-21-27](https://user-images.githubusercontent.com/95756707/169456195-8ae1c822-abbe-42ec-893c-a455b749a1ca.png)

**Comment by sighingnow** [comment]
Looks good! Could you please paste a link for the website here?

Thanks!

**Comment by ShibeFaceSkrill** [comment]
https://docs.shibeface.finance/

thanks to you! 

very happy to find jekyll-gitbook. 

gitbook cli is no longer maintained + much more reasonable to maintain a jekyll theme, vs an entire engine for just 1 theme.

**Comment by sighingnow** [comment]
> 

Thanks. Will implemented today. Glad to see the jekyll-gitbook theme could help.

**Comment by sighingnow** [comment]
Implemented in main.

**Comment by ShibeFaceSkrill** [comment]
oh, thank you! I'm looking forward to the experience!
