### ISSUE TITLE
Topic Categories

### ISSUE THREAD

**Issue by Oreomeow** [sighingnow/jekyll-gitbook#33]
Is it possible to add topic categories? Click on a topic in the left navigation bar to expand the post title.
e.g. https://lawbook.cf 
chapter-fold plugin

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by sighingnow** [comment]
Will be implemented.

**Comment by sighingnow** [comment]
After taking a more careful look into the chapter-hold plugin I decided not to include it in this theme, as the `0-README.md` required much extra manual effort to build such content, especially in Jekyll where the permanent link is auto-generated based on the date pattern (usually).

Instead, Jekyll usually uses a flat content structure.

I'm going to close this issue as won't fix it and will reconsider adding the plugin if I could figure out a better way to auto-generate the index page in the future.

Thanks for your suggestion for this project!
