### ISSUE TITLE
Using custom fonts?

### ISSUE THREAD

**Issue by shiami** [sighingnow/jekyll-gitbook#34]
Any suggestion that I can follow to add custom fonts?

**Comment by sighingnow** [comment]
> Any suggestion that I can follow to add custom fonts?

I could add a configuration entry for fonts.

**Comment by sighingnow** [comment]
Hi @shiami,

The font settings could be customized by adding style entries to `custom.css`, see also the description in commit https://github.com/sighingnow/jekyll-gitbook/commit/c3f4df3af4c35a971bfb42d13d1fda44b98a34ce as well as the README.
