### ISSUE TITLE
Feature Suggestion: Tips, warnings, and danger messages

### ISSUE THREAD

**Issue by Turtlepaw** [sighingnow/jekyll-gitbook#36]
Would it be possible to have tips, warnings, and danger messages, like in gitbook?

**Comment by sighingnow** [comment]
Could you please provides a link for such examples?

**Comment by Turtlepaw** [comment]
https://discordjs.guide/popular-topics/audit-logs.html#some-quick-background

**Comment by sighingnow** [comment]
Thanks.

I will take a look and see how to incorporate such a feature with this jekyll theme and the markdown reader.

**Comment by sighingnow** [comment]
Hi @Turtlepaw,

I would like to let you know that such a feature has been implemented in this theme. See the syntax and rendered page at https://sighingnow.github.io/jekyll-gitbook/jekyll/2022-06-30-tips_warnings_dangers.html

Thanks for your suggestion for such a nice feature!
