### ISSUE TITLE
MD tables only shows a small part in portrait mode on mobile devices

### ISSUE THREAD

**Issue by IOMisaka** [sighingnow/jekyll-gitbook#37]
simple test data

```
|title1|title2|title3|title4|title5|title6|title7|title8|
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|1|2|3|4|5|6|7|8|
|1|2|3|4|5|6|7|8|
|1|2|3|4|5|6|7|8|
|1|2|3|4|5|6|7|8|
```

and there is no scrollbars for the viewer
![msedge_JcxoD6uODW](https://user-images.githubusercontent.com/100711412/174764424-0380cb8a-efeb-40ba-8005-61bce2cdaef5.png)

### update

got an alternative solution to show a scrollbar when writting MD
https://stackoverflow.com/questions/41076390/is-there-a-way-to-overflow-a-markdown-table-using-html

```
<div class="table-wrapper" markdown="block">
*TABLE CONTENT*
</div>
```

css add:

```
.table-wrapper {
  overflow-x: scroll;
}
```

**Comment by sighingnow** [comment]
Thanks for the catch!
