### ISSUE TITLE
Missing custom fonts for book-summary and book-header

### ISSUE THREAD

**Issue by shiami** [sighingnow/jekyll-gitbook#38]
No effect on book-summary and book-header with the custom fonts settings here:
https://github.com/sighingnow/jekyll-gitbook#customizing-font-settings

Need to edit ```/gitbook/style.css```:
```
.book-summary {
    font-family: "CustomFonts";
```

The same for the book-header, add:
```
.book-header {
    font-family: "CustomFonts";
}
```

**Comment by sighingnow** [comment]
Cannot reproduce.

Please make sure the desired fonts have been either installed locally or [imported correctly in CSS](https://www.w3schools.com/css/css3_fonts.asp).
