### ISSUE TITLE
无法页面内跳转到指定位置

### ISSUE THREAD

**Issue by lavendarlash** [sighingnow/jekyll-gitbook#39]
我是小白，实在不懂，求大佬解答

**Comment by sighingnow** [comment]
问题已经解决了么？

**Comment by lavendarlash** [comment]
解决了哥，我太傻了……对不起

从 Windows 版邮件发送

发件人: Tao He
发送时间: 2022年7月11日 9:27
收件人: sighingnow/jekyll-gitbook
抄送: lavendarlash; State change
主题: Re: [sighingnow/jekyll-gitbook] 无法页面内跳转到指定位置 (Issue #39)

问题已经解决了么？

**Comment by sighingnow** [comment]
好的。
