### ISSUE TITLE
Is it possible to use this theme without forking, with with a `docs` folder and `_config.yml` file?

### ISSUE THREAD

**Issue by carlosperate** [sighingnow/jekyll-gitbook#40]
The README instructions indicate to use the theme we have to fork the repo.

GitHub pages also provide the positivily to throw a bunch of markdown files and a `_config.yml` file into a `docs` folder.
I tried that in this repo but it doesn't seem to work well? https://github.com/microbit-carlos/microbit-bird-activity/commit/76ee1b50e95920a99065d6d8239d7c236bdf5a4a
It fails to load these assets:
```
Loading failed for the <script> with source “https://microbit-carlos.github.io/microbit-bird-activity/gitbook/gitbook.js”. [microbit-bird-activity:222:1](https://microbit-carlos.github.io/microbit-bird-activity/)
Loading failed for the <script> with source “https://microbit-carlos.github.io/microbit-bird-activity/gitbook/theme.js”. [microbit-bird-activity:223:1](https://microbit-carlos.github.io/microbit-bird-activity/)
Loading failed for the <script> with source “https://microbit-carlos.github.io/microbit-bird-activity/gitbook/gitbook-plugin-fontsettings/fontsettings.js”. [microbit-bird-activity:225:1](https://microbit-carlos.github.io/microbit-bird-activity/)
Loading failed for the <script> with source “https://microbit-carlos.github.io/microbit-bird-activity/gitbook/gitbook-plugin-sharing/buttons.js”. [microbit-bird-activity:226:1](https://microbit-carlos.github.io/microbit-bird-activity/)
Loading failed for the <script> with source “https://microbit-carlos.github.io/microbit-bird-activity/gitbook/gitbook-plugin-search-pro/jquery.mark.min.js”. [microbit-bird-activity:233:1](https://microbit-carlos.github.io/microbit-bird-activity/)
Loading failed for the <script> with source “https://microbit-carlos.github.io/microbit-bird-activity/gitbook/gitbook-plugin-search-pro/search.js”. [microbit-bird-activity:234:1](https://microbit-carlos.github.io/microbit-bird-activity/)
Loading failed for the <script> with source “https://microbit-carlos.github.io/microbit-bird-activity/gitbook/gitbook-plugin-back-to-top-button/plugin.js”.
```

Is this method of using the theme supported?

**Comment by sighingnow** [comment]
Fork is not a necessity.

You definitely could download the source tarball or clone the repo to anywhere you want.

**Comment by sighingnow** [comment]
> It fails to load these assets:

I would take a look about the failure later.

**Comment by sighingnow** [comment]
I have never tried `remote_theme` on github pages. Looks quite interesting and I would comment here once make some progress.

**Comment by carlosperate** [comment]
Thanks for the quick reply @sighingnow.

The idea would be to not have to include the theme assets anywhere, but let GitHub Pages jekyll remote theme to build it all from just the markdown files.

For example, this this theme: https://github.com/carlosperate/jekyll-theme-rtd
I could build these docs: https://www.embeddedlog.com/ubittool/
With only markdown files and `_config.yml` files contained in this repo folder: https://github.com/carlosperate/ubittool/tree/master/docs 

So GitHub pages automatically fetches the theme from a GitHub repository, builds it and deploys it.

**Comment by sighingnow** [comment]
> So GitHub pages automatically fetches the theme from a GitHub repository, builds it and deploys it.

Thanks for making it clear.

**Comment by sighingnow** [comment]
Hi @carlosperate,

Now `remote_theme` should work as expected, the site itself has been to migrated to use the `remote_theme` as well: https://github.com/sighingnow/jekyll-gitbook/blob/master/_config.yml#L17
