### ISSUE TITLE
Two requests

### ISSUE THREAD

**Issue by Oreomeow** [sighingnow/jekyll-gitbook#45]
In remote_theme mode

- I want to change the share links in the top right corner to my GitHub repository address and telegram group address.
- I want to modify the favicon.ico.

Is this feasible? I look forward to your reply.

**Comment by sighingnow** [comment]
> I want to change the share links in the top right corner to my GitHub repository address and telegram group address.

I would like to see some examples and your desired views.

> I want to modify the favicon.ico.

I would provide an option for it.

**Comment by Oreomeow** [comment]
> > I want to change the share links in the top right corner to my GitHub repository address and telegram group address.
> 
> I would like to see some examples and your desired views.
> 
> > I want to modify the favicon.ico.
> 
> I would provide an option for it.

[assets/gitbook/gitbook-plugin-sharing/buttons.js](https://github.com/sighingnow/jekyll-gitbook/blob/a104416637e5ddc637bfa0356dbb234a9f782c80/assets/gitbook/gitbook-plugin-sharing/buttons.js#L2)

```js
    var SITES = {
        'github': {
            'label': 'GitHub',
            'icon': 'fa fa-github',
            'onClick': function(e) {
                e.preventDefault();
                window.open('https://github.com/Oreomeow');
            }
        },
        'telegram': {
            'label': 'Telegram',
            'icon': 'fa fa-paper-plane',
            'onClick': function(e) {
                e.preventDefault();
                window.open('https://t.me/joinchat/muGNhnaZglQ0N2Q1');
            }
        }
```

[_includes/metadata.json.tpl](https://github.com/sighingnow/jekyll-gitbook/blob/a104416637e5ddc637bfa0356dbb234a9f782c80/_includes/metadata.json.tpl#L24)

```tpl
            "sharing": {
                "all": ["facebook", "google", "twitter", "weibo", "instapaper"],
                "facebook": true,
                // "all": ["facebook", "google", "twitter", "weibo", "instapaper"],
                "github": true,
                "telegram": true,
                "facebook": false,
                "google": false,
                "instapaper": false,
                "twitter": true,
                "twitter": false,
                "vk": false,
                "weibo": false
            },
```

Thanks!

**Comment by Oreomeow** [comment]
btw, modify apple-touch-icon-precomposed-152.png also

**Comment by sighingnow** [comment]
> I want to modify the favicon.ico.

A new config entry for favicon.ico has been added in https://github.com/sighingnow/jekyll-gitbook/commit/9c9fde129738485cfb3e962c9f06c4be274ddaa9

**Comment by sighingnow** [comment]
> I want to change the share links in the top right corner to my GitHub repository address and telegram group address.

A separate `_includes/gitbook-sharing.json.tpl` has been added to tweak the gitbook sharing plugin configuration. You could update the `"github"` and `"github_link"` entries for github, and `"telegram"` and `"telegram_link"` for telegram, respectively.

(You can has a customized `_includes/gitbook-sharing.json.tpl` under your own project root directory to overwrite the default configuration.)

**Comment by sighingnow** [comment]
Closing as implemented on main.

**Comment by Oreomeow** [comment]
> > I want to change the share links in the top right corner to my GitHub repository address and telegram group address.
> 
> A separate `_includes/gitbook-sharing.json.tpl` has been added to tweak the gitbook sharing plugin configuration. You could update the `"github"` and `"github_link"` entries for github, and `"telegram"` and `"telegram_link"` for telegram, respectively.
> 
> (You can has a customized `_includes/gitbook-sharing.json.tpl` under your own project root directory to overwrite the default configuration.)

I tried, but it failed. Would you check for me?
