### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by SHI3DO** [sighingnow/jekyll-gitbook#46]
I changed the post of 2019-04-28 to 2022-08-14, but it seems to have disappeared. I have tried to reload the site several times, but no posts have been returned. I checked that the date is set as a variable in the code, what's the problem? The same goes for all the other posts.

**Comment by sighingnow** [comment]
Hi @SHI3DO,

You could try to delete the `_site/` directory under your project home and run `bundle exec jekyll serve` again to see if it appears in your left-side TOC tree.

**Comment by SHI3DO** [comment]
Thank you for this wonderful Jekyll theme! It worked 👍
