### ISSUE TITLE
Sharing button bug

### ISSUE THREAD

**Issue by ghost** [sighingnow/jekyll-gitbook#47]
> > I want to change the share links in the top right corner to my GitHub repository address and telegram group address.
> 
> A separate `_includes/gitbook-sharing.json.tpl` has been added to tweak the gitbook sharing plugin configuration. You could update the `"github"` and `"github_link"` entries for github, and `"telegram"` and `"telegram_link"` for telegram, respectively.
> 
> (You can has a customized `_includes/gitbook-sharing.json.tpl` under your own project root directory to overwrite the default configuration.)

I tried, but it failed. Would you check for me?

It looks like something went wrong.

- ![image](https://user-images.githubusercontent.com/62660101/184527473-af2ad244-bf4b-47a9-8dc5-85e0e40ede22.png)

_Originally posted by @Oreomeow in https://github.com/sighingnow/jekyll-gitbook/issues/45#issuecomment-1214304090_

**Comment by sighingnow** [comment]
Will take a try.

**Comment by sighingnow** [comment]
Fixed on main.
