### ISSUE TITLE
CSS styles and pages do not work

### ISSUE THREAD

**Issue by igorhoop** [sighingnow/jekyll-gitbook#53]
Hi. I did Fork your project and set it up as a source on Github Pages, but CSS styles do not work and links to other pages are referenced incorrectly.

You can watch it on
https://igorhoop.github.io/hoop_docs/

Sorry for stupid question, I haven't fully studied Jekyll yet

**Comment by sighingnow** [comment]
You need change your `baseurl` to `hoop_docs/`.

See: https://github.com/sighingnow/jekyll-gitbook/blob/master/_config.yml#L13
