### ISSUE TITLE
Potentially Unintended Mobile Behavior

### ISSUE THREAD

**Issue by memorylick** [sighingnow/jekyll-gitbook#56]
Hi! I'm loving the theme and want to use it for a book-style website, but I ran into one(-ish) weirdness. The desktop version is borderline perfect, but I have a few questions regarding the header buttons' behavior in mobile mode. I understand why this happens, and that this is completely tied to the width of the window (it only happens in portrait mode), but I lack brains to solve it myself.

Can these buttons become hidden on mobile when the left-side menu is open?
![mobile-header-buttons-problem](https://user-images.githubusercontent.com/60663493/207224113-734b98d6-3a1e-4e2d-96db-733b5b48ea35.jpg)

With menu open they don't have much functionality in portrait mode anyway, because of things like this:
![mobile-header-buttons-useless-1](https://user-images.githubusercontent.com/60663493/207224169-25a2ff1a-b5c8-4e89-b016-185abbfc5212.jpg)
![mobile-header-buttons-useless-2](https://user-images.githubusercontent.com/60663493/207224214-db681e92-15ac-460e-bb76-3690ed420369.jpg)

A whole other part of the problem is that the buttons become glued to the top of the window, along with the menu button, so you can't close the menu unless you scroll all the way up or tap on a chapter (this also happens on desktop if the window is made very narrow):
https://user-images.githubusercontent.com/60663493/207224503-b4014dc2-d33a-44cd-97d5-53e4cd5b2a08.mp4

Can the menu button (or all of them, for that matter) be unglued from the top in mobile/narrow window with the menu open (when the header collapses and the buttons align vertically)?

Sorry for rolling two issues into one, but I recognize that these can be considered extremely pedantic non-problems, so please consider this posting a question rather than a bug report.

**Comment by sighingnow** [comment]
Fixed.

**Comment by memorylick** [comment]
thank you! 🙏
