### ISSUE TITLE
could gitbook-theme support comments?

### ISSUE THREAD

**Issue by winterpi** [sighingnow/jekyll-gitbook#63]
thank you all guys for this great theme. I like it very much.  It's very clean.

but I'd like to have a comments function for this theme, I also searched for gitalk for comments.
Do you know how to integrate with this theme?

**Comment by sighingnow** [comment]
Good idea. I would take a try to adding such comment systems into this theme.

**Comment by sighingnow** [comment]
Disqus has been added in https://github.com/sighingnow/jekyll-gitbook/commit/9bd8539a573aa7c35d8d752f8c233501f909ed5d
