### ISSUE TITLE
pages load pre-scrolled on mobile webkit

### ISSUE THREAD

**Issue by memorylick** [sighingnow/jekyll-gitbook#69]
I am absolutely in love with this theme and super grateful for its existence, and maybe I just care too much about inconsequential stuff, but I have discovered yet another strange "problem" on mobile. It seems that in Chromium-based mobile browsers gitbook pages have a tendency to load slightly pre-scrolled (initially discovered in Safari on gf's iphone and then confirmed in Chrome on both iOS and Android). Only happens on a fresh load or a page refresh: if you go to a different page via the side menu, it will open properly, and all the other pages of the website from that point on will load as expected too, but if you then refresh the page, it will load slightly pre-scrolled again. I tried tinkering with parts of the code that mention webkit, but couldn't identify the root of this behavior.

![prescrolled-1](https://user-images.githubusercontent.com/60663493/222884625-551ed57d-06ed-42d9-bb5b-ff6fb0c80978.jpg)
![prescrolled-2](https://user-images.githubusercontent.com/60663493/222884626-884a154e-0f15-44fa-a8df-04e3b11dedc2.jpg)
![prescrolled-3](https://user-images.githubusercontent.com/60663493/222884628-d0e301b1-d2f5-410d-8fc5-a0c82f146c89.jpg)

https://user-images.githubusercontent.com/60663493/222884629-94370860-b8d2-4292-ab6b-057dbd668aa3.mp4

**Comment by sighingnow** [comment]
Should have been addressed in main.
