### ISSUE TITLE
horizontally scrollable header on mobile webkit when side menu open

### ISSUE THREAD

**Issue by memorylick** [sighingnow/jekyll-gitbook#70]
Thank you so much for addressing the formatting that led me to this! 🙏 Here is yet another strange mobile webkit-exclusive thing that I randomly discovered when viewing the theme in Safari. With side menu open the header is interpreted as a horizontally scrollable field allowing for a little bit of wobble.

https://user-images.githubusercontent.com/60663493/222884922-607740c9-c740-425f-8873-975737f6b556.mp4

I apologize for keeping reporting such petty things.

**Comment by sighingnow** [comment]
Fixed.
