### ISSUE TITLE
snippet of code in html 'details' tag

### ISSUE THREAD

**Issue by denispeyrusaubes** [sighingnow/jekyll-gitbook#75]
I'd like to insert code into my details html tag : 

<details>
<summary>blah</summary>
```
ls -al
```
</details>

But the theme does not interpret the code snippet into my `detail` tag.

Any idea ?

**Comment by sighingnow** [comment]
The markdown is processed and rendered as HTML by kramdown.

See also: https://github.com/gettalong/kramdown/issues/155
