### ISSUE TITLE
How to make the search button work?

### ISSUE THREAD

**Issue by chengjun** [sighingnow/jekyll-gitbook#8]
Thank you for contributing this excellent theme. I really like it. I guess it could support the search function using lunr. But I am not familiar with the code. Would you mind share your opinion about how to make the search function work within this theme? Thank you!

**Comment by sighingnow** [comment]
I think that is doable, by integratiing some kind of js search library into website, like what "Read The Docs" sites do. I think the difficult is how to let github pages to generate such kind of index.

If github pages cannot do that(github pages is a restrict jekyll environment), we then need the js library to generate such kind of index instead.

**Comment by sighingnow** [comment]
I think we could borrow stuffs from https://github.com/jekylltools/jekyll-tipue-search, it looks pretty promising.

**Comment by chengjun** [comment]
@sighingnow thank you very much for this reply. I will try this solution and report the result later.

**Comment by chengjun** [comment]
> @sighingnow thank you very much for this reply. I will try this solution and report the result later.

I have tried to add the jekyll-tipue-search into this theme, check this url https://data-journalism.github.io/search/ . But it seems there is something wrong. BTW, it seems that it could not support the searching of the Chinese language.

**Comment by sighingnow** [comment]
> > @sighingnow thank you very much for this reply. I will try this solution and report the result later.
> 
> I have tried to add the jekyll-tipue-search into this theme, check this url https://data-journalism.github.io/search/ . But it seems there is something wrong. BTW, it seems that it could not support the searching of the Chinese language.

Thanks for your effort! I will try and implements such features in this repo this weekend.

**Comment by sighingnow** [comment]
Hi @chengjun,

I would like you to know that the search function has been added to the master branch, and you can try it out at: https://sighingnow.github.io/jekyll-gitbook/search/?q=generated

**Comment by sighingnow** [comment]
Hi @chengjun I would like you to now that now the search button is implemented using the gitbook-plugin-search-pro plugin and yields the exactly same UI and behaviour with gitbook itself.

**Comment by chengjun** [comment]
WOW, that is brilliant! Thanks a lot!
