### ISSUE TITLE
How to update MathJax ?

### ISSUE THREAD

**Issue by ZenMoore** [sighingnow/jekyll-gitbook#9]
There is something wrong when it comes to math formula processing !
see here : https://zenmoore.github.io/theory/2021-09-21-structuralentropygraph.html
I have no idea why it happens and how can I deal with it ?
source codes : https://github.com/ZenMoore/zenmoore.github.io

**Comment by sighingnow** [comment]
For things like 

```
$\begin{aligned} \mathcal{H}^{1}(G) &=H(\mathbf{p})=H\left(\frac{d_{1}}{2 m}, \ldots, \frac{d_{n}}{2 m}\right) \\ &=-\sum_{i=1}^{n} \frac{d_{i}}{2 m} \cdot \log _{2} \frac{d_{i}}{2 m} . \end{aligned}$
```

I think you need `$$` (for multi-line formulas) for such blocks.
