### ISSUE TITLE
feature: easy allow extra level of `custom.css` in remote usage context

### ISSUE THREAD

**Issue by marc-portier** [sighingnow/jekyll-gitbook#91]
The theme currently uses a `custom.css` (in `assests/gitbook/`) for special local settings.

However if people use the theme in a `jekyll-remote-theme` setting this obliges them to copy and extend the file in order to add own extra entries.

i would like to suggest 
- introduce an extra `custom-local.css` that is just empty (apart from a comment declaring its intent)
- that is imported at the end of custom.css
- that can then safely be filled in locally to add extra useful style rules...

if you like this idea, I will gladly work up the PR

**Comment by sighingnow** [comment]
Looks quite a good feature. Thanks for proposing and working on that! A pull request would definitely be high appreciated!

Thanks!
