### ISSUE TITLE
bug: book.with-summary is fighting with the drop-down menus

### ISSUE THREAD

**Issue by marc-portier** [sighingnow/jekyll-gitbook#93]
as a side effect of looking to #73 I noticed that he drop down menus (on the left for font + background, on the right for sharing) do not work if the summary-side bar is active.

I see the style-effects are still correctly applied (the `.open` class is added to the correct `div.dropdown`) but somehow that does not make the menus actually pop up.

I assume (for now) there is a conflict between the `book.with-summary` leading to `left: 0` applied on a higher level.  Would need more investigation, but wanted to share already in case somebody has a quicker eye on this.

**Comment by marc-portier** [comment]
never mind my earlier `left:0` remark -- that just works nicely to show-hide the summary.

I just did a quick comparison with the original gitbook style on some other site...
and it looks like the `div.body-inner` is missing from our style

it seems to add the needed context to reset some positions:
![image](https://github.com/sighingnow/jekyll-gitbook/assets/299574/7806858f-6163-4a31-82d0-13a2c727c92f)

**Comment by sighingnow** [comment]
Fixed by https://github.com/sighingnow/jekyll-gitbook/commit/2075f8e6f22e88f7b694eddb13f8e3cee56f172d and https://github.com/sighingnow/jekyll-gitbook/commit/676cf700c5311af748c6daa7609728574f64e5b7.
